const categories = [
    "Electrónica",
    "Moda y ropa",
    "Hogar y decoración",
    "Belleza y cuidado personal",
    "Deportes y fitness",
    "Juguetes y juegos",
    "Libros y literatura",
    "Joyería y accesorios",
    "Arte y manualidades",
    "Alimentos y bebidas",
    "Salud y bienestar",
    "Automóviles y accesorios",
    "Muebles y decoración del hogar",
    "Instrumentos musicales",
    "Tecnología y gadgets",
    "Películas y música",
    "Herramientas y mejoras del hogar",
    "Jardinería y paisajismo",
    "Productos para mascotas",
    "Suministros para oficina",
    "Equipamiento deportivo",
    "Productos para bebés y maternidad",
    "Viajes y accesorios de viaje",
    "Artículos de coleccionismo",
    "Calzado y zapatos",
    "Ropa de deporte y equipos",
    "Instrumentos médicos y suministros",
    "Productos ecológicos y sostenibles",
    "Suministros de limpieza y organización",
    "Cámaras y fotografía"
  ];
  
  module.exports = categories;
  